services:

  elasticsearch:
    image: elasticsearch:9.0.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true

    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      
volumes:
  elasticsearch-data:
